spring:
  datasource:
    name: competition
    url: jdbc:mysql://localhost:3306/competition?serverTimezone=UTC
    username: root
    password: ilyf1314520
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    schema: classpath:competition.sql # schema.sql中一般存放的是DDL脚本，即通常为创建或更新库表的脚本
    initialization-mode: always

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    maxIdle: 300    #最大空闲数
    maxTotal: 1000  #控制一个pool可分配多少个jedis实例,
    maxWaitMillis: 1000   #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    minEvictableIdleTimeMillis: 30000   #连接的最小空闲时间 默认1800000毫秒(30分钟)
    testOnBorrow: true #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testWhileIdle: #在空闲时检查有效性, 默认false


mybatis:
  mapperLocations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.xxq.competition.entity # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true #开启驼峰自动转换

server:
  port: 8099


  http:
    multipart:
      enabled: true #默认支持文件上传. 
      file-size-threshold: 0 #支持文件写入磁盘.
      location: .  # 上传文件的临时目录 
      max-file-size: 1Mb # 最大支持文件大小 
      max-request-size: 10Mb # 最大支持请求大小



