spring:
  datasource:
    name: competition
    url: jdbc:mysql://localhost:3306/competition?serverTimezone=UTC
    username: root
    password: ilyf1314520
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    schema: classpath:competition.sql # schema.sql中一般存放的是DDL脚本，即通常为创建或更新库表的脚本
    initialization-mode: always
mybatis:
  mapperLocations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.xxq.competition.entity # 注意：对应实体类的路径

server:
  port: 8099
  http:
    multipart:
      enabled: true #默认支持文件上传. 
      file-size-threshold: 0 #支持文件写入磁盘.
      location: .  # 上传文件的临时目录 
      max-file-size: 1Mb # 最大支持文件大小 
      max-request-size: 10Mb # 最大支持请求大小

